### ISSUE TITLE
sdtether has mixed spaces and tabs, python2 style print statements - Fails to execute

### ISSUE THREAD

**Issue by Sowmya-R-Krishnan** [CBDD/rDock#10]
Dear rDock team,

sdrmsd issue has been reported in an earlier issue - sdtether also has similar issues. Several lines of code have indentation issue and multiple print statements also have problem since they are missing parantheses. Please fix these issues in the code for the users.

Thanks
Sowmya

**Comment by CCEN1020** [comment]
Hello, have you solved this issue? I downloaded the **rdock-23.12.126_ubuntu-22.04_g++_x86_64.tar.gz** version, and the sdrmsd still has this problem.

**Comment by ggutierrez-sunbright** [comment]
Hi,

it's still not done, but we're working on it. I'll do a quick fix for sdtether so we can close this issue, and @lpardey is finishing a full refactor of sdrmsd as part of #59
I expect those to be available in the main branch by the end of this week.

regards

**Comment by ggutierrez-sunbright** [comment]
Hi,

after #67 and #68 (kudos to @lpardey), the updated versions of `sdrmsd` and `sdtether` are available.
please note the versions may still need changes and improvements (`sdrmsd` has some tests at least, but `sdtether` is in (pre)alpha version)

in order to install the latest version of rdock-utils, you could either:
1. Clone the repository
2. open a terminal in the root folder
3. run `pip install ./rdock-utils`

or:
1. directly run `pip install "git+https://git@github.com/CBDD/rDock.git#subdirectory=rdock-utils"`

the scripts should be readily available once the installation is complete.

please let me know if you find problems while installing or running the scripts
i'll keep this issue open for that purpose.

thanks and regards

**Comment by ggutierrez-sunbright** [comment]
I detected a typo, that was fixed by #69

**Comment by CCEN1020** [comment]
> Hi,
> 
> after #67 and #68 (kudos to @lpardey), the updated versions of `sdrmsd` and `sdtether` are available. please note the versions may still need changes and improvements (`sdrmsd` has some tests at least, but `sdtether` is in (pre)alpha version)
> 
> in order to install the latest version of rdock-utils, you could either:
> 
> 1. Clone the repository
> 2. open a terminal in the root folder
> 3. run `pip install ./rdock-utils`
> 
> or:
> 
> 1. directly run `pip install "git+https://git@github.com/CBDD/rDock.git#subdirectory=rdock-utils"`
> 
> the scripts should be readily available once the installation is complete.
> 
> please let me know if you find problems while installing or running the scripts i'll keep this issue open for that purpose.
> 
> thanks and regards

The new code is usable, thank you.

**Comment by ggutierrez-sunbright** [comment]
> 
> The new code is usable, thank you.

Hi,

thanks for confirming. I'll close this ticket, but feel free to reopen (or create a new one) if you find any further issue

regards
